services:
  address-db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - address-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=address
    healthcheck:
      test: pg_isready -U postgres -d address -h localhost -p 5432
      interval: 10s
      timeout: 5s
      retries: 3
  address:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://address-db:5432/address
      - SPRING_FLYWAY_URL=jdbc:postgresql://address-db:5432/address
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: wget http://localhost:8080/graphiql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    depends_on:
      address-db:
        condition: service_healthy
  address-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "address",
      "--app-port", "8080",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:address"
volumes:
  address-db-data: